### ISSUE TITLE
运行多次之后报错，求解

### ISSUE THREAD

**Issue by JerryTian0** [universeindream/MaiCaiAssistant#22]
Build version: 2.1.0 
Build date: 1981-01-01 01:01:02 
Current date: 2022-04-12 10:43:56 
Device: HUAWEI BLA-AL00 
OS version: Android 6.0.1 (SDK 23) 
 
Stack trace:  
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6552)
	at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:942)
	at android.view.ViewGroup.invalidateChild(ViewGroup.java:5081)
	at android.view.View.invalidateInternal(View.java:12719)
	at android.view.View.invalidate(View.java:12683)
	at android.view.View.invalidate(View.java:12667)
	at android.widget.TextView.checkForRelayout(TextView.java:7156)
	at android.widget.TextView.setText(TextView.java:4347)
	at android.widget.TextView.setText(TextView.java:4204)
	at android.widget.TextView.setText(TextView.java:4179)
	at com.univerindream.maicaiassistant.service.GlobalActionBarService.updateSnapUpButton(GlobalActionBarService.kt:220)
	at com.univerindream.maicaiassistant.service.GlobalActionBarService.cancelTask(GlobalActionBarService.kt:208)
	at com.univerindream.maicaiassistant.service.GlobalActionBarService.access$cancelTask(GlobalActionBarService.kt:26)
	at com.univerindream.maicaiassistant.service.GlobalActionBarService$runLoop$1.invokeSuspend(GlobalActionBarService.kt:136)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by itwangxiang** [comment]
已修复
