### ISSUE TITLE
一加9开启辅助权限后报错，app无法打开

### ISSUE THREAD

**Issue by 200542053** [universeindream/MaiCaiAssistant#31]
一加9开启辅助权限后报错，app无法打开

ERROR DETAILS内容：

Build version: 2.1.6 
Build date: 1981-01-01 01:01:02 
Current date: 2022-04-13 19:37:05 
Device: OnePlus LE2121 
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.RuntimeException: Unable to create service com.univerindream.maicaiassistant.service.GlobalActionBarService: java.lang.IllegalArgumentException: com.univerindream.maicaiassistant: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4662)
	at android.app.ActivityThread.access$100(ActivityThread.java:253)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2203)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8184)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Caused by: java.lang.IllegalArgumentException: com.univerindream.maicaiassistant: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:378)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:461)
	at android.app.PendingIntent.getActivity(PendingIntent.java:447)
	at android.app.PendingIntent.getActivity(PendingIntent.java:411)
	at com.univerindream.maicaiassistant.MHUtil.startForegroundService(MHUtil.kt:189)
	at com.univerindream.maicaiassistant.service.GlobalActionBarService.onCreate(GlobalActionBarService.kt:44)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4649)
	... 9 more

**Comment by itwangxiang** [comment]
v2.1.7
