### ISSUE TITLE
悬浮窗闪了一下就没了 系统鸿蒙2.0

### ISSUE THREAD

**Issue by yyk802388** [universeindream/MaiCaiAssistant#4]
就那个有三个选项的组件  开启无障碍后  点开软件  闪了一下就没了   软件界面也正常   直接设置时间开启定时抢购  到时间后  开关自动就关掉了

**Comment by 424778940z** [comment]
三星完全看不见悬浮窗...

**Comment by zhangkai0804** [comment]
+1

**Comment by maxmilia** [comment]
小米开启无障碍后也没有那个组件显示

**Comment by summerzo** [comment]
Realme开启无障碍没有那三个按钮........

**Comment by saberxt** [comment]
同楼主，悬浮窗一下子就没了，mate30pro，鸿蒙系统

**Comment by itwangxiang** [comment]
理论上已经修复，需要的话，可以试试

**Comment by saberxt** [comment]
还是不行

https://user-images.githubusercontent.com/103311994/162661603-c6a66dc1-a1cb-4c97-88a6-4e3569405604.mp4

**Comment by 1abner1** [comment]
同样遇到上述问题

**Comment by is2ac-zhao** [comment]
应该是这个app没有申请悬浮窗权限，没办法在其他应用上显示

**Comment by 1abner1** [comment]
有解决方法吗？谢谢

**Comment by saberxt** [comment]
Build version: 2.1.0 
Build date: 1981-01-01 01:01:02 
Current date: 2022-04-12 00:50:45 
Device: HUAWEI LIO-AN00 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at com.univerindream.maicaiassistant.service.GlobalActionBarService.onAccessibilityEvent(GlobalActionBarService.kt:87)
	at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1635)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1824)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by 1abner1** [comment]
谢谢，已经有浮动窗口了，可以使用了-v2.13  版。虽然源文件是v2.13 ,但是安装的时候显示的还是v2.
![微信图片_20220412102901](https://user-images.githubusercontent.com/71709614/162867876-41058812-d28d-49fc-9558-c8814b6ac46e.jpg)

**Comment by 1abner1** [comment]
谢谢，已经有浮动窗口了，可以使用了-v2.13  版。虽然源文件是v2.13 ,但是安装的时候显示的还是v2.还是有点不稳定
